name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
          context: .
          push: false
          tags: catalinii/minisatip-build-image:latest
